---
title: "Test table to SBtab to SBML"
author: "Marie Corradi"
date: "10/08/2021"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
conda_create("ontox-app", python_version = "3.8")
conda_install("ontox-app", "sbtab", pip = FALSE)
use_condaenv("ontox-app", required = TRUE)
```

```{r}
file_test <- here::here('liver_bile_example','liver_bile_relations.tsv')

# t1 <- read.table(file_test, sep="\t", fill=TRUE, header=FALSE, quote="")
# 
# # Convert table to string that can be recognized as SBtab object later on
# temp <- toString(t1)
# temp <- paste(do.call(paste, c(temp, sep="\t")), collapse="\n")

```


```{python}
import sbtab
import libsbml
from sbtab import SBtab
from sbtab import validatorSBtab
from sbtab import sbtab2sbml
from pathlib import Path

# from SBtab import SBtabTable
# from validatorSBtab import ValidateTable
# from sbtab2sbml import SBtabDocument


# Read in TSV file containing SBtab info. CSV also works
sbtab_file = open(r.file_test,'r')
file_content = sbtab_file.read()
sbtab_file.close()

# Make SBtab object
Sd = SBtab.SBtabDocument()
Sd.set_filename('liver_bile_relations.tsv')
Sd.set_name('liver_bile_example')
Sd.add_sbtab_string(file_content,filename='liver_bile_relations.tsv')

# Validate the SBtab file and save warnings
V_obj = validatorSBtab.ValidateDocument(Sd)
warnings = V_obj.validate_document()
print(warnings)

# Convert SBtab file to SBML
Cd = sbtab2sbml.SBtabDocument(Sd)
(sbml, warnings) = Cd.convert_to_sbml('31')

# Save SBML xml file (overwrites existing file with the same name)
myfile = open("liver_bile_relations.xml", "w")
myfile.write(sbml)
myfile.close()
```

```{r}
sessionInfo()
```

