---
title: "test"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Packages
```{r packages}
library(tidyverse)
library(here)

```


## Data load
```{r load}
sbtab_defenitions <- read_tsv(
  here(
    "columns", "definitions.tsv"
  ), 
  comment = "!!"
)
```


## Clean column labels
```{r clean}
colnames(sbtab_defenitions) <- c("ComponentName", 
                                 "ComponentType", 
                                 "IsPartOf", 
                                 "Format", 
                                 "Description"
                                 )
```


## Sort tables by IsPartOf 
```{r sort}
compartment_cols <- sbtab_defenitions %>%
  filter(
    IsPartOf == "Compartment"
    ) %>% 
  transmute(
    ComponentName
    ) %>% 
  t() %>% as_tibble()
colnames(compartment_cols) <- compartment_cols[1,]

compound_cols <- sbtab_defenitions %>%
  filter(
    IsPartOf == "Compound"
    ) %>% 
  transmute(
    ComponentName
    ) %>% 
  t() %>% as_tibble()
colnames(compound_cols) <- compound_cols[1,]

definition_cols <- sbtab_defenitions %>%
  filter(
    IsPartOf == "Definition"
    ) %>% 
  transmute(
    ComponentName
    ) %>% 
  t() %>% as_tibble()
colnames(definition_cols) <- definition_cols[1,]

enzyme_cols <- sbtab_defenitions %>%
  filter(
    IsPartOf == "Enzyme"
    ) %>% 
  transmute(
    ComponentName
    ) %>% 
  t() %>% as_tibble()
colnames(enzyme_cols) <- enzyme_cols[1,]

gene_cols <- sbtab_defenitions %>%
  filter(
    IsPartOf == "Gene"
    ) %>% 
  transmute(
    ComponentName
    ) %>% 
  t() %>% as_tibble()
colnames(gene_cols) <- gene_cols[1,]

protein_cols <- sbtab_defenitions %>%
  filter(
    IsPartOf == "Protein"
    ) %>% 
  transmute(
    ComponentName
    ) %>% 
  t() %>% as_tibble()
colnames(protein_cols) <- protein_cols[1,]

quantity_cols <- sbtab_defenitions %>%
  filter(
    IsPartOf == "Quantity"
    ) %>% 
  transmute(
    ComponentName
    ) %>% 
  t() %>% as_tibble()
colnames(quantity_cols) <- quantity_cols[1,]

quantitymatrix_cols <- sbtab_defenitions %>%
  filter(
    IsPartOf == "QuantityMatrix"
    ) %>% 
  transmute(
    ComponentName
    ) %>% 
  t() %>% as_tibble()
colnames(quantitymatrix_cols) <- quantitymatrix_cols[1,]

reaction_cols <- sbtab_defenitions %>%
  filter(
    IsPartOf == "Reaction"
    ) %>% 
  transmute(
    ComponentName
    ) %>% 
  t() %>% as_tibble()
colnames(reaction_cols) <- reaction_cols[1,]

regulator_cols <- sbtab_defenitions %>%
  filter(
    IsPartOf == "Regulator"
    ) %>% 
  transmute(
    ComponentName
    ) %>% 
  t() %>% as_tibble()
colnames(regulator_cols) <- regulator_cols[1,]

relation_cols <- sbtab_defenitions %>%
  filter(
    IsPartOf == "Relation"
    ) %>% 
  transmute(
    ComponentName
    ) %>% 
  t() %>% as_tibble()
colnames(relation_cols) <- relation_cols[1,]

stoichiometricmatrix_cols <- sbtab_defenitions %>%
  filter(
    IsPartOf == "StoichiometricMatrix"
    ) %>% 
  transmute(
    ComponentName
    ) %>% 
  t() %>% as_tibble()
colnames(stoichiometricmatrix_cols) <- stoichiometricmatrix_cols[1,] 

```


## Convert sorted tables to CSV
```{r convert}
#Create function for better reproducibility 
df_to_csv <- function(df, path){
  readr::write_csv(
    df,
    file = here::here(
      path,
      paste0(deparse(substitute(df)), ".csv"
             )
    )
  )
  }

#Use function to write the sorted tables to CSV
df_to_csv(compound_cols, "columns")
df_to_csv(compartment_cols, "columns")
df_to_csv(definition_cols, "columns")
df_to_csv(enzyme_cols, "columns")
df_to_csv(gene_cols, "columns")
df_to_csv(protein_cols, "columns")
df_to_csv(quantity_cols, "columns")
df_to_csv(quantitymatrix_cols, "columns")
df_to_csv(reaction_cols, "columns")
df_to_csv(regulator_cols, "columns")
df_to_csv(relation_cols, "columns")
df_to_csv(stoichiometricmatrix_cols, "columns")
```

